	USE MASTER	
	SELECT 10+20			--	ADDITION
	SELECT 'HCL'+ 'TECHNOLOGIES'	--	 STRING CONCATENATION
	SELECT	10-5			--	SUBTRACTION
	SELECT	10*10			--	MULTIPLICATION
	SELECT	100/10			--	DIVISION
	SELECT	100%4			--	MODULUS
	SELECT	=			--	ASSIGNMENT, EQUALITY
 	SELECT  &			--	BITWISE AND
	SELECT	|			--	BITWISE OR
