USE PUBS
UPDATE AUTHORS
    		SET AUTHORS.AU_FNAME = 'Deannnnn'
    		WHERE AU_FNAME = 'Dean'
SELECT AU_FNAME FROM AUTHORS

UPDATE AUTHORS
    		SET AUTHORS.AU_FNAME = 'Dean'
    		WHERE AU_FNAME = 'Deannnnn'
SELECT AU_FNAME FROM AUTHORS